- build/packages.bootstrap.config
- src/CommerceModel.BetterRetail/CommerceModel.BetterRetail.csproj
- src/CommerceModel.BetterRetail/packages.config
> Updating Orckestra.Installer to 4.0.56 and PsUtil to 1.0.44

- build/nuget.config
- nuget.config
This reverts commit 66e64756418cca253b63f7ae82b91a62186ab112.
> Revert "Update PAT in nuget files (#10)"

- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateStoresActivity/BetterRetailCanada/Quebec/CreateOrUpdateStore409.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateStoresActivity/BetterRetailCanada/Quebec/CreateOrUpdateStore410.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateStoresActivity/BetterRetailCanada/Quebec/CreateOrUpdateStore411.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateStoresActivity/BetterRetailCanada/Quebec/CreateOrUpdateStore414.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateStoresActivity/BetterRetailCanada/Quebec/CreateOrUpdateStore433.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateStoresActivity/BetterRetailCanada/Quebec/CreateOrUpdateStore526.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateStoresActivity/BetterRetailNetherlands/CreateOrUpdateStore5101.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateStoresActivity/BetterRetailNetherlands/CreateOrUpdateStore5102.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateStoresActivity/BetterRetailNetherlands/CreateOrUpdateStore5103.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateStoresActivity/BetterRetailNetherlands/CreateOrUpdateStore5104.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateStoresActivity/BetterRetailNetherlands/CreateOrUpdateStore5105.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateStoresActivity/BetterRetailNetherlands/CreateOrUpdateStore5106.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateStoresActivity/BetterRetailNorway/CreateOrUpdateStore9101.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateStoresActivity/BetterRetailNorway/CreateOrUpdateStore9102.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateStoresActivity/BetterRetailNorway/CreateOrUpdateStore9103.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateStoresActivity/BetterRetailNorway/CreateOrUpdateStore9104.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateStoresActivity/BetterRetailNorway/CreateOrUpdateStore9105.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateStoresActivity/BetterRetailNorway/CreateOrUpdateStore9106.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateWarehousesActivity/BetterRetailCanada/CreateOrUpdateWarehouse5000.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateWarehousesActivity/BetterRetailNetherlands/CreateOrUpdateWarehouse5004.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateWarehousesActivity/BetterRetailNorway/CreateOrUpdateWarehouse5003.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateWarehousesActivity/BetterRetailUSA/CreateOrUpdateWarehouse5001.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/QueueImportProfileSchemaActivity/profiles.json
Add FF Location setting to require barcode scans to capture quantities picked in MSF
Story: #40482
> Add FF Location setting to require barcode to be scanned

- src/CommerceModel.BetterRetail.Activities/CommerceModel.BetterRetail.Activities.csproj
- src/CommerceModel.BetterRetail.Activities/packages.config
- src/CommerceModel.BetterRetail/CommerceModel.BetterRetail.csproj
- src/CommerceModel.BetterRetail/CopyArtifacts.targets
- src/CommerceModel.BetterRetail/artifacts/OCS/App_Data/Workflows/Orders/BetterRetail/DefaultCartTotalWorkflow.xaml
- src/CommerceModel.BetterRetail/artifacts/OCS/App_Data/Workflows/Orders/BetterRetail/DefaultOrderTotalWorkflow.xaml
- src/CommerceModel.BetterRetail/packages.config
> Fixed the creation of the nuget package for CMP

- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/QueueOrderSchemaImportActivity/providers.json
- Have only one moneris payment provider per scope
Story [AB#48543](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/48543)
> Have only one moneris payment provider per scope

- src/CommerceModel.BetterRetail/artifacts/OCS-OOE/Search/solr.products.ALL.config
> Removed the "Lifestyle" field from SOLR config

- src/CommerceModel.BetterRetail/CommerceModel.BetterRetail.csproj
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/ExecuteSQLScriptActivity/Order/AddExternalPaymentProvider.sql
Include the AddExternalPaymentProvider.sql script in the CommerceModel so ExternalPaymentProvider entries are added to database once the LoadDataProfile_DevTest is run
> Create ExternalPaymentProvider for Bambora in CommerceModel

- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/ExecuteSQLScriptActivity/Order/AddExternalPaymentProvider.sql
Corrections to API routes and DisplayName entries
> Corrections to ExternalPaymentProvider for Bambora in CommerceModel

- src/CommerceModel.BetterRetail/LoadDataProfile_DevTest.xaml
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CommerceModelDefinition.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateStoresActivity/BetterRetailUSA/California/CreateOrUpdateStore100.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateStoresActivity/BetterRetailUSA/Florida/CreateOrUpdateStore101.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/CreateStoresActivity/BetterRetailUSA/Hawaii/CreateOrUpdateStore102.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/QueueOrderSchemaImportActivity/providers.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/QueueProductCatalogsImportsActivity/BetterRetailCanada-Catalog-v1.0/catalogs.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/QueueProductCatalogsImportsActivity/BetterRetailNetherlands-Catalog-v1.0/catalogs.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/QueueProductCatalogsImportsActivity/BetterRetailNorway-Catalog-v1.0/catalogs.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/QueueProductCatalogsImportsActivity/BetterRetailUSA-Catalog-v1.0/catalogs.json
Include US scopes, locations and providers. Also fix catalog expiry dates
> Include US scopes, locations and providers. Also fix catalog expiry dates

- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/QueueProductCatalogsImportsActivity/BetterRetailCanada-Catalog-v1.0/catalogs.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/QueueProductCatalogsImportsActivity/BetterRetailNetherlands-Catalog-v1.0/catalogs.json
- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/QueueProductCatalogsImportsActivity/BetterRetailUSA-Catalog-v1.0/catalogs.json
Remove endDate from catalogs that used them
> Remove endDate from catalogs that used them

- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/ExecuteSQLScriptActivity/Order/AddExternalPaymentProvider.sql
Get right payment URL in env QA
[AB#57661](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/57661)
> Update to use default int webapp for qa

- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/ExecuteSQLScriptActivity/Order/AddExternalPaymentProvider.sql
[AB#57533](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/57533)
> Add new payment profile endpoint

- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/ExecuteSQLScriptActivity/Order/AddExternalPaymentProvider.sql
This reverts commit a2a84734e207c6e0ee591c64dcf6806401357e61.
[AB#57533](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/57533)
> Revert "Add new payment profile endpoint"

- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/ExecuteSQLScriptActivity/Order/AddExternalPaymentProvider.sql
[AB#57533](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/57533)
> Add CreateCartPaymentVaultProfileUrl

- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/QueueOrderSchemaImportActivity/lookups.json
Need to add new Order Lookup ExternalPaymentMethodType
Values : ApplePay -> Apple pay
[AB#56662](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/56662)
> Add ApplePay lookup

- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/ExecuteSQLScriptActivity/Order/AddExternalPaymentProvider.sql
File was UTF-8 BOM updated to UTF-8
[AB#57533](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/57533)
> Fix url issue related to encoding

- build/build-pipeline.yml
[AB#59484](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/59484)
> Update build-pipeline to allow LFS

- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/QueueProfilesImportActivity/BetterRetailProfiles.zip
Bugs [AB#61178](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/61178)
> Fix add the corresponding zip file

- src/CommerceModel.BetterRetail.Activities/CommerceModel.BetterRetail.Activities.csproj
- src/CommerceModel.BetterRetail.Activities/app.config
- src/CommerceModel.BetterRetail.Activities/packages.config
- src/CommerceModel.BetterRetail/CommerceModel.BetterRetail.csproj
- src/CommerceModel.BetterRetail/app.config
- src/CommerceModel.BetterRetail/packages.config
[AB#60632](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/60632)
> Newtonsoft upgrade to v13

- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/QueueOrderSchemaImportActivity/lookups.json
US [AB#55271](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/55271)
> Add PaymentHistory lookup

- src/CommerceModel.BetterRetail/CommerceModel.BetterRetail.csproj
Fixing missing BetterRetailCanada.json file content
> Fixing missing BetterRetailCanada.json file content

- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/QueueOrderSchemaImportActivity/lookups.json
[AB#64023](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/64023)
> Fix typos in payment history lookup

- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/QueueOrderSchemaImportActivity/lookups.json
[AB#64203](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/64203)
> Add missing and fix PaymentHistory lookups

- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/QueueOrderSchemaImportActivity/providers.json
Update Moneris profile ids for store 2 and 5
Story [AB#62789](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/62789)
> Update Moneris profile ids for store 2 and 5

- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/QueueOrderSchemaImportActivity/providers.json
Moneris token for store 2 updated
Story [AB#62789](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/62789)
> Moneris token for store 2 updated

- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/QueueOrderSchemaImportActivity/providers.json
Update authentication credential for microservice
US [AB#62351](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/62351)
> Update authentication credential for microservice

- src/CommerceModel.BetterRetail/artifacts/OOE/BetterRetail/QueueOrderSchemaImportActivity/providers.json
[AB#66572](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/66572)
> Adjust BetterRetailUSA AvalaraTaxProvider that had been truncated

- .gitignore
Have Git ignore sensitive data file
Story [AB#66679](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/66679)
> Have Git ignore sensitive data file
